const About  = () => {
    return (<>

     <section className='flex items-center p-8 flex-col w-4/5 mx-auto min-h-screen'>
          <h2 className='font-bold p-3 text-4xl'>About US</h2>
          <div className="text-justify">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi doloribus ratione, nobis dicta, rerum sint facere hic autem, voluptatem fugiat fuga! Quo accusamus nesciunt alias mollitia velit dolor tempora vero? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil voluptas ducimus cum, facere dolore accusantium officia velit sapiente pariatur fugit quo, optio quibusdam voluptatem voluptate placeat, totam eum vero tempore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel expedita voluptatibus dolore? Voluptate magni earum quasi, vero voluptatem saepe numquam odit delectus. Quaerat officiis qui architecto dolore! Harum, asperiores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde, soluta! Ex, doloremque. Nobis eaque in atque quae, eum laudantium accusamus debitis reprehenderit corrupti? Hic nesciunt quis necessitatibus magni quia dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id quia optio ad quod excepturi laborum quo aut, corporis repellat, quos maxime, nemo eveniet incidunt molestias? Voluptatem sed recusandae magnam facilis. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora harum culpa officia nulla maxime illo amet expedita at, cupiditate ab reprehenderit deserunt assumenda excepturi dolor natus laborum doloribus quasi quas!</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi doloribus ratione, nobis dicta, rerum sint facere hic autem, voluptatem fugiat fuga! Quo accusamus nesciunt alias mollitia velit dolor tempora vero? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil voluptas ducimus cum, facere dolore accusantium officia velit sapiente pariatur fugit quo, optio quibusdam voluptatem voluptate placeat, totam eum vero tempore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel expedita voluptatibus dolore? Voluptate magni earum quasi, vero voluptatem saepe numquam odit delectus. Quaerat officiis qui architecto dolore! Harum, asperiores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde, soluta! Ex, doloremque. Nobis eaque in atque quae, eum laudantium accusamus debitis reprehenderit corrupti? Hic nesciunt quis necessitatibus magni quia dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id quia optio ad quod excepturi laborum quo aut, corporis repellat, quos maxime, nemo eveniet incidunt molestias? Voluptatem sed recusandae magnam facilis. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora harum culpa officia nulla maxime illo amet expedita at, cupiditate ab reprehenderit deserunt assumenda excepturi dolor natus laborum doloribus quasi quas!</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi doloribus ratione, nobis dicta, rerum sint facere hic autem, voluptatem fugiat fuga! Quo accusamus nesciunt alias mollitia velit dolor tempora vero? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil voluptas ducimus cum, facere dolore accusantium officia velit sapiente pariatur fugit quo, optio quibusdam voluptatem voluptate placeat, totam eum vero tempore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel expedita voluptatibus dolore? Voluptate magni earum quasi, vero voluptatem saepe numquam odit delectus. Quaerat officiis qui architecto dolore! Harum, asperiores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde, soluta! Ex, doloremque. Nobis eaque in atque quae, eum laudantium accusamus debitis reprehenderit corrupti? Hic nesciunt quis necessitatibus magni quia dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Id quia optio ad quod excepturi laborum quo aut, corporis repellat, quos maxime, nemo eveniet incidunt molestias? Voluptatem sed recusandae magnam facilis. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora harum culpa officia nulla maxime illo amet expedita at, cupiditate ab reprehenderit deserunt assumenda excepturi dolor natus laborum doloribus quasi quas!</p>
          </div>
      </section>  

    </>)
};

export default About